import './globals.css'
import { Montserrat } from 'next/font/google'

import NavBar from '@/components/NavBar/NavBar'
import Footer from '@/components/Footer/Footer'

const bodyFont = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
